### ISSUE TITLE
[Register add-on on the official website]:  TEST (Outlook extended)

### ISSUE THREAD

**Issue by CyrilleB79** [nvdaes/addonFiles#6]
### Download URL

https://github.com/CyrilleB79/outlookExtended/releases/download/V1.7/outlookExtended-1.7.nvda-addon

### Add-on repository

https://github.com/CyrilleB79/outlookExtended/

### Terms of use

- [X] The add-on has been tested and reviewed according to processes

**Comment by CyrilleB79** [comment]
Nothing to do of course, this is just a test.

**Comment by nvdaes** [comment]
The url for now is fixed in GitHub Actions, for testing. So the retrieved info is for clipContentsDesigner. To check registration on the website wit mrconfig you may use the repo on the gitub organization (from mobile).

**Comment by CyrilleB79** [comment]
Seems it does not yet take the real add-on name.
Was it just for a demo purpose?

In any case, it is very nice.

Two little things to note as feedback in addition:
* In the future, think to add-ons that have a stable download link and a dev download link
* Field "Add-on maintainer": it's clear if the maintainer differs from the reporter. But if it is the same person (which will be the majority of cases), I did not understand clearly if I need to put my Github name or nothing.
* Regarding the checkbox "The add-on has been tested and reviewed according to processes", a link to the process would be required

Of course, I know it is only a PoC in alpha stage.

**Comment by CyrilleB79** [comment]
OK thanks.
Test finished now.

**Comment by nvdaes** [comment]
Thanks for suggestion. I thought about the dev and stable links. For example @AbuffErr prefers a template instead of using forms, I think Also, I don"t know where addonFiles goe to end of use. So I think athat a markdown template would be more likely used, since people have to know the addon key in get.php and changes maybe required. But this maybe useful to learn and I will use something similar for conributors of our community website (one of the websites available for NVDA in spanish community), in case some people wants to contribute without being added as a collaborator. Also it maybe used for addonFiles or for the store if needed, but I tend to send a markdown template for pull request in addonFiles, to NVAccess, and improve the form for mr config.  will consider your useful suggestions

Enviado desde mi iPhone

**Comment by CyrilleB79** [comment]
IMO the form are nice if you need to use the provided data for automatic actions such as GitHub action to download and check the add-on. On a markdown template, there is more risk to have some information wrongly formatted as an input of the action.
But on the other hand, I agree that markdown is simpler to set up and to maintain. And for developers, especially add-on developers, filling a markdown template should not be a problem, overall as long as NVDA repo also uses it.
